esphome:
  name: button
  friendly_name: Button
  name_add_mac_suffix: True

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf

packages: !include common/base.yaml
api:
logger:
captive_portal:

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: Button Fallback Hotspot

event:
  - platform: template
    name: Button
    id: button_event
    device_class: button
    event_types:
      - short
      - double
      - triple
      - long
      - short_long

output:
  - platform: ledc
    id: buzzer_output
    pin: GPIO2
    max_power: 0.1

script:
  - id: buzzer_alarm
    then:
      - repeat:
          count: 4
          then:
            - output.turn_on: buzzer_output
            - delay: 400ms
            - output.turn_off: buzzer_output
            - delay: 400ms
button:
  - platform: template
    name: Trigger Alarm
    on_press:
      then:
        - script.execute: buzzer_alarm

binary_sensor:
  # Hardware button on GPIO
  - platform: gpio
    id: hw_button
    internal: True
    pin:
      number: 3
      mode:
        input: true
        pulldown: true
      inverted: false
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_multi_click:
      # Single Short Click
      - timing:
          - ON for at most 750ms
          - OFF for at least 300ms
        then:
          - event.trigger:
              id: button_event
              event_type: short

      # Double Click: two quick presses
      - timing:
          - ON for at most 750ms
          - OFF for at most 300ms
          - ON for at most 750ms
          - OFF for at least 300ms
        then:
          - event.trigger:
              id: button_event
              event_type: double

      # Triple Click: three quick presses
      - timing:
          - ON for at most 750ms
          - OFF for at most 300ms
          - ON for at most 750ms
          - OFF for at most 300ms
          - ON for at most 750ms
          - OFF for at least 300ms
        then:
          - event.trigger:
              id: button_event
              event_type: triple

      # Short then Long: first short, then long press
      - timing:
          - ON for at most 750ms
          - OFF for at most 300ms
          - ON for at least 750ms
        then:
          - event.trigger:
              id: button_event
              event_type: short_long

      # Long Press only
      - timing:
          - ON for at least 750ms
        then:
          - event.trigger:
              id: button_event
              event_type: long
