esphome:
  name: button
  friendly_name: Button
  name_add_mac_suffix: True

esp32:
  board: esp32-c3-devkitc-02
  framework:
    type: esp-idf

packages: !include common/base.yaml
api:
captive_portal:

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: Button Fallback Hotspot

event:
  - platform: template
    name: Button
    id: button_event
    device_class: button
    event_types:
      - short
      - double
      - triple
      - long
      - short_long

binary_sensor:
  # Hardware button on GPIO
  - platform: gpio
    id: hw_button
    internal: True
    pin:
      number: 3
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_multi_click:
      # Single Short Click
      - timing:
          - ON for at most 750ms
          - OFF for at least 300ms
        then:
          - event.trigger:
              id: button_event
              event_type: short

      # Double Click: two quick presses
      - timing:
          - ON for at most 750ms
          - OFF for at most 300ms
          - ON for at most 750ms
          - OFF for at least 300ms
        then:
          - event.trigger:
              id: button_event
              event_type: double

      # Triple Click: three quick presses
      - timing:
          - ON for at most 750ms
          - OFF for at most 300ms
          - ON for at most 750ms
          - OFF for at most 300ms
          - ON for at most 750ms
          - OFF for at least 300ms
        then:
          - event.trigger:
              id: button_event
              event_type: triple

      # Short then Long: first short, then long press
      - timing:
          - ON for at most 750ms
          - OFF for at most 300ms
          - ON for at least 750ms
        then:
          - event.trigger:
              id: button_event
              event_type: short_long

      # Long Press only
      - timing:
          - ON for at least 750ms
        then:
          - event.trigger:
              id: button_event
              event_type: long
