esphome:
  name: button
  friendly_name: Button
  name_add_mac_suffix: True

esp32:
  board: esp32-c3-devkitc-02
  framework:
    type: esp-idf

logger:
api:

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True
  ap:
    ssid: "Button Fallback Hotspot"
    password: swablab!

button:
  - platform: restart
    name: "Restart"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "ESP Uptime"
    update_interval: 60s

event:
  - platform: template
    name: Event
    id: button_event
    device_class: button
    event_types:
      - short
      - double
      - long
      - short_long

binary_sensor:
  # Hardware button on GPIO
  - platform: gpio
    id: hw_button
    internal: True
    pin:
      number: 3
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_multi_click:
      - timing:
          - ON for at most 300ms
          - OFF for at least 300ms
        then:
          - event.trigger:
              id: button_event
              event_type: short
      - timing:
          - ON for at most 300ms
          - OFF for at most 300ms
          - ON for at most 300ms
          - OFF for at least 300ms
        then:
          - event.trigger:
              id: button_event
              event_type: double
      - timing:
          - ON for at most 300ms
          - OFF for at most 300ms
          - ON for at least 500ms
        then:
          - event.trigger:
              id: button_event
              event_type: short_long
      - timing:
          - ON for at least 500ms
        then:
          - event.trigger:
              id: button_event
              event_type: long

output:
  - platform: ledc
    pin: 0
    id: led_red
  - platform: ledc
    pin: 1
    id: led_green
  - platform: ledc
    pin: 2
    id: led_blue

light:
  - platform: rgb
    name: LED
    id: led
    blue: led_blue
    green: led_green
    red: led_red
    default_transition_length:
      milliseconds: 100
