esphome:
  name: office-desk
  friendly_name: Office Desk
  area: Office
  name_add_mac_suffix: True

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

logger:
api:

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

binary_sensor:
  - platform: gpio
    id: button
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    pin:
      number: D4
      mode:
        input: True
        pullup: True
