esphome:
  name: sensorbox
  friendly_name: Sensorbox
  min_version: 2024.6.0
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf

packages:
  - !include common/base.yaml

logger:
api:
ota:
- platform: esphome
  password: !secret ota_password
improv_serial:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Sensorbox"
captive_portal:
web_server:

uart:
  - tx_pin: GPIO10
    rx_pin: GPIO09
    baud_rate: 9600
    id: uart_ze08
    parity: none
    data_bits: 8
    stop_bits: 1
  - tx_pin: GPIO08
    rx_pin: GPIO07
    baud_rate: 9600
    id: uart_pms

spi:
  clk_pin: GPIO01
  mosi_pin: GPIO02
  miso_pin: GPIO16

i2c:
  - sda: GPIO11
    scl: GPIO12
    scan: true
    id: i2c_main
  - sda: GPIO17
    scl: GPIO18
    scan: true
    id: i2c_2

#region SENSORS
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
      inverted: true
    id: top_btn
    filters:
      - delayed_on: 10ms
      - delayed_off: 20ms
    on_click:
      then:
        - lambda: |-
            auto brightness = int(id(back_light).current_values.get_brightness() * 255);
            if (brightness > 128) {
              id(back_light).turn_on().set_brightness(0.5).perform();
            } else if (brightness > 64) {
              id(back_light).turn_on().set_brightness(0.25).perform();
            } else if (brightness > 16) {
              id(back_light).turn_on().set_brightness(0.05).perform();
            } else {
              id(back_light).turn_on().set_brightness(1.0).perform();
            }
    on_double_click:
      then:
        - display.page.show_next: display_main
        - component.update: display_main

sensor:
  - platform: aht10
    #address: 0x38
    i2c_id: i2c_main
    variant: AHT20
    temperature:
      name: "Temperature"
      id: temp_aht20
    humidity:
      name: "Humidity"
      id: hum_aht20
  - platform: bmp280_i2c
    address: 0x77
    i2c_id: i2c_main
    temperature:
      name: "BMP280 Temperature"
      id: temp_bmp280
      oversampling: 16x
      internal: True
    pressure:
      name: "Pressure"
      id: pres_bmp280
  - platform: scd4x
    #address: 0x62
    i2c_id: i2c_main
    co2:
      name: "CO2"
      id: co2_scd40
    temperature:
      name: "SCD40 Temperature"
      id: temp_scd40
      internal: True
    humidity:
      name: "SCD40 Humidity"
      id: hum_scd40
      internal: True
  - platform: sgp30
    i2c_id: i2c_main
    address: 0x58
    eco2:
      name: "eCO2"
      id: eco2_sgp30
      accuracy_decimals: 0
      filters:
        - exponential_moving_average:
            send_every: 1
            alpha: 0.2
    tvoc:
      name: "TVOC"
      state_class: "measurement"
      unit_of_measurement: "ppb"
      id: tvoc_sgp30
      accuracy_decimals: 1
      filters:
        - exponential_moving_average:
            send_every: 1
            alpha: 0.2
    store_baseline: yes
    compensation:
      humidity_source: hum_aht20
      temperature_source: temp_aht20
  - platform: pmsx003
    type: PMSX003
    uart_id: uart_pms
    pm_1_0:
      name: PM1.0
      id: pm1_0_pms
    pm_2_5:
      name: PM2.5
      id: pm2_5_pms
    pm_10_0:
      name: PM10
      id: pm10_0_pms
#endregion SENSORS

#region DISPLAY SETUP
color:
  - id: white
    hex: FFFFFF
  - id: gray
    hex: AAAAAA
  - id: light_gray
    hex: CCCCCC
  - id: dark_gray
    hex: 555555
  - id: green
    hex: A1FFA4
  - id: lime
    hex: D7FF61
  - id: yellow
    hex: FFF047
  - id: orange
    hex: FFBC58
  - id: red
    hex: FF0000
  - id: purple
    hex: FF33DD

font:
  - file: "gfonts://Montserrat@900"
    id: font_value
    size: 72
    bpp: 4
    glyphs: ["0","1","2","3","4","5","6","7","8","9",".","-","n","a"]
  - file: "gfonts://Montserrat@900"
    id: font_value_small
    size: 52
    bpp: 4
    glyphs: ["0","1","2","3","4","5","6","7","8","9",".","-","n","a"]
  - file: "gfonts://Montserrat@900"
    id: font_value_huge
    size: 90
    bpp: 4
    glyphs: ["0","1","2","3","4","5","6","7","8","9",".","-","n","a"]
  - file: "gfonts://Montserrat@600"
    id: font_label
    size: 20
    bpp: 4
    glyphs: [" ",".","0","1","2","5",A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z]

psram:
  mode: quad
  speed: 80MHz

output:
  - platform: ledc
    pin: GPIO15
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    icon: mdi:cellphone
    name: "Display"
    id: back_light
    restore_mode: ALWAYS_ON
#endregion DISPLAY SETUP

#region DISPLAY
display:
  - platform: ili9xxx
    id: display_main
    model: ILI9341
    cs_pin: GPIO03
    dc_pin: GPIO04
    reset_pin: GPIO06
    transform:
      mirror_y: true
    color_order: bgr
    invert_colors: false
    color_palette: 8BIT
    dimensions:
      height: 320
      width: 240
    pages:
      - id: page_main
        lambda: |-
          // Get sensor values
          float temperature = id(temp_aht20).state;
          float humidity = id(hum_aht20).state;
          float pressure = id(pres_bmp280).state;
          auto co2 = id(co2_scd40).state;
          auto tvoc = id(tvoc_sgp30).state;
          auto pm1_0 = id(pm1_0_pms).state;
          auto pm2_5 = id(pm2_5_pms).state;
          auto pm10_0 = id(pm10_0_pms).state;

          // CO2 Scale
          auto color_co2 = id(white);
          if      (co2 <   600) color_co2 = id(green);
          else if (co2 <   800) color_co2 = id(lime);
          else if (co2 <  1000) color_co2 = id(yellow);
          else if (co2 <  1500) color_co2 = id(orange);
          else if (co2 >= 1500) color_co2 = id(red);

          // TVOC Scale
          auto color_tvoc = id(white);
          if      (tvoc <   100) color_tvoc = id(green);
          else if (tvoc <   300) color_tvoc = id(lime);
          else if (tvoc <   500) color_tvoc = id(yellow);
          else if (tvoc <  1000) color_tvoc = id(orange);
          else if (tvoc >= 1000) color_tvoc = id(red);

          // PM1.0 Scale
          auto color_pm1_0 = id(white);
          if      (pm1_0 <   5) color_pm1_0 = id(green);
          else if (pm1_0 <  15) color_pm1_0 = id(lime);
          else if (pm1_0 <  25) color_pm1_0 = id(yellow);
          else if (pm1_0 <  35) color_pm1_0 = id(orange);
          else if (pm1_0 >= 35) color_pm1_0 = id(red);

          // PM2.5 Scale
          auto color_pm2_5 = id(white);
          if      (pm2_5 <   5) color_pm2_5 = id(green);
          else if (pm2_5 <  15) color_pm2_5 = id(lime);
          else if (pm2_5 <  25) color_pm2_5 = id(yellow);
          else if (pm2_5 <  35) color_pm2_5 = id(orange);
          else if (pm2_5 >= 35) color_pm2_5 = id(red);

          // PM10 Scale
          auto color_pm10_0 = id(white);
          if      (pm10_0 <   15) color_pm10_0 = id(green);
          else if (pm10_0 <   45) color_pm10_0 = id(lime);
          else if (pm10_0 <   75) color_pm10_0 = id(yellow);
          else if (pm10_0 <  150) color_pm10_0 = id(orange);
          else if (pm10_0 >= 150) color_pm10_0 = id(red);

          auto w = it.get_width();
          auto h = it.get_height();
          auto offset_y = 5;

          auto draw_divider = [&](int &y) {
            y += offset_y;
            it.line(10, y, w - 10, y, dark_gray);
            y += offset_y;
          };

          auto draw_main = [&](int &y) {
            auto col = w / 1;
            auto h_label = id(font_label)->get_height();
            auto h_value = id(font_value)->get_height();

            it.print(0.5 * col, y, id(font_label), light_gray, TextAlign::TOP_CENTER, "Temp");
            it.printf(0.5 * col, y + h_label, id(font_value), white, TextAlign::TOP_CENTER, "%.1f", temperature);

            y += h_label + h_value;
          };

          auto draw_header = [&](int &y) {
            auto col = w / 2;
            auto h_label = id(font_label)->get_height();
            auto h_value = id(font_value_small)->get_height();

            it.print(0.5 * col, y, id(font_label), light_gray, TextAlign::TOP_CENTER, "CO2");
            it.printf(0.5 * col, y + h_label, id(font_value_small), color_co2, TextAlign::TOP_CENTER, "%.0f", co2);

            it.print(1.5 * col, y, id(font_label), light_gray, TextAlign::TOP_CENTER, "VOC");
            it.printf(1.5 * col, y + h_label, id(font_value_small), color_tvoc, TextAlign::TOP_CENTER, "%.0f", tvoc);

            y += h_label + h_value;
          };

          auto draw_footer = [&](int &y) {
            auto col = w / 3;
            auto h_label = id(font_label)->get_height();
            auto h_value = id(font_value_small)->get_height();

            it.print(0.5 * col, y, id(font_label), light_gray, TextAlign::TOP_CENTER, "PM10");
            it.printf(0.5 * col, y + h_label, id(font_value_small), color_pm10_0, TextAlign::TOP_CENTER, "%.0f", pm10_0);

            it.print(1.5 * col, y, id(font_label), light_gray, TextAlign::TOP_CENTER, "PM2.5");
            it.printf(1.5 * col, y + h_label, id(font_value_small), color_pm2_5, TextAlign::TOP_CENTER, "%.0f", pm2_5);

            it.print(2.5 * col, y, id(font_label), light_gray, TextAlign::TOP_CENTER, "PM1");
            it.printf(2.5 * col, y + h_label, id(font_value_small), color_pm1_0, TextAlign::TOP_CENTER, "%.0f", pm1_0);

            y += h_label + h_value;
          };

          auto cy = 8;

          draw_header(cy);
          draw_divider(cy);
          draw_main(cy);
          draw_divider(cy);
          draw_footer(cy);
      - id: page_screensaver
        lambda: |-
          auto w = it.get_width();
          auto h = it.get_height();

          // Get sensor values
          auto temperature = id(temp_aht20).state;
          auto co2 = id(co2_scd40).state;

          it.printf(w / 2, h / 2, id(font_value_huge), id(white), TextAlign::CENTER, "%.1f", temperature);
#endregion DISPLAY
