esphome:
  name: sensorbox
  friendly_name: Sensorbox
  min_version: 2024.6.0
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf

packages: !include common/base.yaml

logger:
api:
ota:
- platform: esphome
  password: !secret ota_password
improv_serial:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Sensorbox"
captive_portal:
web_server:

uart:
  - tx_pin: GPIO10
    rx_pin: GPIO09
    baud_rate: 9600
    id: uart_ze08
    parity: none
    data_bits: 8
    stop_bits: 1
  - tx_pin: GPIO08
    rx_pin: GPIO07
    baud_rate: 9600
    id: uart_pms

spi:
  clk_pin: GPIO01
  mosi_pin: GPIO02
  miso_pin: GPIO16

i2c:
  - sda: GPIO11
    scl: GPIO12
    scan: true
    id: i2c_main
  - sda: GPIO17
    scl: GPIO18
    scan: true
    id: i2c_2

#region SENSORS
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
      inverted: true
    id: top_btn
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_click:
      then:
        - lambda: |-
            auto brightness = int(id(back_light).remote_values.get_brightness() * 255);
            if (brightness > 128) {
              id(back_light).turn_on().set_brightness(0.5).perform();
            } else if (brightness > 64) {
              id(back_light).turn_on().set_brightness(0.25).perform();
            } else if (brightness > 16) {
              id(back_light).turn_on().set_brightness(0.05).perform();
            } else {
              id(back_light).turn_on().set_brightness(1.0).perform();
            }

sensor:
  - platform: aht10
    #address: 0x38
    i2c_id: i2c_main
    variant: AHT20
    temperature:
      name: "Temperature"
      id: temp_aht20
    humidity:
      name: "Humidity"
      id: hum_aht20
    update_interval: 10s
  - platform: bmp280_i2c
    address: 0x77
    i2c_id: i2c_main
    temperature:
      name: "BMP280 Temperature"
      id: temp_bmp280
      oversampling: 16x
      internal: True
    pressure:
      name: "Pressure"
      id: pres_bmp280
    update_interval: 10s
  - platform: scd4x
    #address: 0x62
    i2c_id: i2c_main
    co2:
      name: "CO2"
      id: co2_scd40
    temperature:
      name: "SCD40 Temperature"
      id: temp_scd40
      internal: True
    humidity:
      name: "SCD40 Humidity"
      id: hum_scd40
      internal: True
    update_interval: 10s
  - platform: sgp30
    i2c_id: i2c_main
    address: 0x58
    eco2:
      name: "eCO2"
      id: eco2_sgp30
      accuracy_decimals: 0
      filters:
        - exponential_moving_average:
            send_every: 1
            alpha: 0.2
    tvoc:
      name: "TVOC"
      state_class: "measurement"
      unit_of_measurement: "ppb"
      id: tvoc_sgp30
      accuracy_decimals: 1
      filters:
        - exponential_moving_average:
            send_every: 1
            alpha: 0.2
    store_baseline: yes
    update_interval: 10s
    compensation:
      humidity_source: hum_aht20
      temperature_source: temp_aht20
#endregion SENSORS

#region DISPLAY SETUP
color:
  - id: white
    hex: FFFFFF
  - id: gray
    hex: AAAAAA
  - id: light_gray
    hex: CCCCCC
  - id: dark_gray
    hex: 555555
  - id: green
    hex: 80FF70
  - id: lime
    hex: C3FF60
  - id: yellow
    hex: FFE040
  - id: orange
    hex: FF993D
  - id: red
    hex: FF3333

font:
  - file: "gfonts://Rubik@400"
    id: font_labels
    size: 14
    bpp: 4
    glyphs: [
      "0","1","2","3","4","5","6","7","8","9", "µ", "³",  "/", "°", "%", ",", ".", "(", ")", "-", "_", ":", A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z," ",a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z
      ]
  - file: "gfonts://Rubik@400"
    id: font_aside
    size: 24
    bpp: 4
    glyphs: [
      "0","1","2","3","4","5","6","7","8","9",".","-"
      ]
  - file: "gfonts://Rubik@600"
    id: font_values
    size: 60
    bpp: 4
    glyphs: [
      "0","1","2","3","4","5","6","7","8","9",".","-"
      ]
  - file: "gfonts://Orbitron@500"
    id: font_headings
    size: 26
    bpp: 4
    glyphs: [
      " ","2",A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z
      ]

psram:
  mode: quad
  speed: 80MHz

output:
  - platform: ledc
    pin: GPIO15
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display"
    id: back_light
    restore_mode: ALWAYS_ON
#endregion DISPLAY SETUP

#region DISPLAY
display:
  - platform: ili9xxx
    model: ILI9341
    cs_pin: GPIO03
    dc_pin: GPIO04
    reset_pin: GPIO06
    transform:
      mirror_y: true
    color_order: bgr
    invert_colors: false
    color_palette: 8BIT
    lambda: |-
      it.fill(Color::BLACK);

      auto w = it.get_width();
      auto h = it.get_height();
      auto offset_x = 10;
      auto offset_y = 10;

      // Get sensor values
      float temperature = id(temp_aht20).state;
      float humidity = id(hum_aht20).state;
      float pressure = id(pres_bmp280).state;
      auto co2 = id(co2_scd40).state;
      auto voc = id(tvoc_sgp30).state;

      // Set current color for sensor values based on thresholds
      auto color_co2 = id(green);
      if (co2 >  600) color_co2 = id(lime);
      if (co2 >  800) color_co2 = id(yellow);
      if (co2 > 1100) color_co2 = id(orange);
      if (co2 > 1400) color_co2 = id(red);

      auto color_voc = id(green);
      if (voc >  200) color_voc = id(lime);
      if (voc >  600) color_voc = id(yellow);
      if (voc > 1000) color_voc = id(orange);
      if (voc > 1500) color_voc = id(red);

      auto cy = 0;

      // Draw top row with temp, hum, pressure
      it.printf( 60, 24, id(font_aside), gray, TextAlign::BOTTOM_RIGHT, "%.1f", temperature);
      it.printf( 63, 14, id(font_labels), dark_gray, TextAlign::BOTTOM_LEFT, "°C");

      it.printf(125, 24, id(font_aside), gray, TextAlign::BOTTOM_RIGHT, "%.0f", humidity);
      it.printf(127, 14, id(font_labels), dark_gray, TextAlign::BOTTOM_LEFT, "%c", '%');

      it.printf(205, 24, id(font_aside), gray, TextAlign::BOTTOM_RIGHT, "%.0f", pressure);
      it.printf(210, 14, id(font_labels), dark_gray, TextAlign::BOTTOM_LEFT, "hPa");
      cy += 26;

      // Draw rows with air quality readings
      auto draw_row = [&](int &cy, const char* title, const char* unit, const char* format, float value, const Color &value_color) {
        it.line(0, cy, w, cy, dark_gray);
        cy += offset_y;
        it.print(offset_x, cy - 8, id(font_headings), light_gray, TextAlign::TOP_LEFT, title);
        it.print(w - offset_x, cy + 6, id(font_labels), gray, TextAlign::TOP_RIGHT, unit);
        it.printf(w - offset_x, cy + 16, id(font_values), value_color, TextAlign::TOP_RIGHT, format, value);
        cy += 74 + offset_y;
      };

      draw_row(cy, "CO2", "ppm", "%.0f", co2, color_co2);
      draw_row(cy, "VOC", "ppb", "%.0f", voc, color_voc);
      draw_row(cy, "Temp", "°C", "%.1f", temperature, white);
    dimensions:
      height: 320
      width: 240
#endregion DISPLAY
