esphome:
  name: sensorbox
  friendly_name: Sensorbox
  min_version: 2024.6.0
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf

packages:
  - !include common/base.yaml

api:
ota:
  - platform: esphome
    password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: Sensorbox
captive_portal:

uart:
  - id: uart_ze08
    tx_pin: GPIO10
    rx_pin: GPIO09
    baud_rate: 9600
    parity: none
    data_bits: 8
    stop_bits: 1
  - id: uart_pms
    tx_pin: GPIO08
    rx_pin: GPIO07
    baud_rate: 9600

spi:
  clk_pin: GPIO01
  mosi_pin: GPIO02
  miso_pin: GPIO16

i2c:
  - id: i2c_main
    sda: GPIO11
    scl: GPIO12
    scan: true
  - id: i2c_2
    sda: GPIO17
    scl: GPIO18
    scan: true

psram:
  mode: quad
  speed: 80MHz

script:
  - id: cycle_backlight_brightness
    then:
      - lambda: |-
          auto brightness = id(back_light).current_values.get_brightness();
          if (brightness > 0.5) {
            id(back_light).turn_on().set_brightness(0.5).perform();
          } else if (brightness > 0.25) {
            id(back_light).turn_on().set_brightness(0.25).perform();
          } else if (brightness > 0.1) {
            id(back_light).turn_on().set_brightness(0.1).perform();
          } else {
            id(back_light).turn_on().set_brightness(1.0).perform();
          }

#region SENSORS
binary_sensor:
  - platform: gpio
    id: btn_top
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_multi_click:
      - timing: # single short press
          - ON for at most 750ms
          - OFF for at least 300ms
        then:
          - script.execute: cycle_backlight_brightness
      - timing: # double short press
          - ON for at most 750ms
          - OFF for at most 300ms
          - ON for at most 750ms
          - OFF for at least 300ms
        then:
      - timing: # triple short press
          - ON for at most 750ms
          - OFF for at most 300ms
          - ON for at most 750ms
          - OFF for at most 300ms
          - ON for at most 750ms
          - OFF for at least 300ms
        then:
      - timing: # single short press, then long press
          - ON for at most 750ms
          - OFF for at most 300ms
          - ON for at least 750ms
        then:
      - timing: # long press
          - ON for at least 750ms
        then:
          - display.page.show_next: display_main
          - component.update: display_main

sensor:
  - platform: aht10
    i2c_id: i2c_main
    variant: AHT20
    update_interval: 30s
    temperature:
      id: aht20_temp
      name: Temperature
    humidity:
      id: aht20_hum
      name: Humidity
  - platform: bmp280_i2c
    i2c_id: i2c_main
    address: 0x77
    update_interval: 30s
    pressure:
      id: bmp280_pressure
      name: Pressure
  - platform: scd4x
    i2c_id: i2c_main
    update_interval: 60s
    co2:
      id: co2_scd40
      name: CO2
  - platform: sgp30
    i2c_id: i2c_main
    address: 0x58
    update_interval: 60s
    tvoc:
      id: sgp30_tvoc
      name: TVOC
      state_class: measurement
      unit_of_measurement: ppb
      accuracy_decimals: 1
    store_baseline: true
    tvoc_baseline:
      id: tvoc_baseline
      name: TVOC Baseline
    compensation:
      humidity_source: aht20_hum
      temperature_source: aht20_temp
  - platform: pmsx003
    type: PMSX003
    uart_id: uart_pms
    update_interval: 3min
    pm_1_0:
      id: pms_pm1
      name: PM1.0
    pm_2_5:
      id: pms_pm2_5
      name: PM2.5
    pm_10_0:
      id: pms_pm10
      name: PM10
  - platform: aqi
    name: Air Quality Index
    pm_2_5: pms_pm2_5
    pm_10_0: pms_pm10
    calculation_type: CAQI
#endregion SENSORS

#region DISPLAY SETUP
color:
  - id: white
    hex: FFFFFF
  - id: light_gray
    hex: CCCCCC
  - id: dark_gray
    hex: 555555
  - id: color_excellent
    hex: 00E400
  - id: color_good
    hex: DCE400
  - id: color_moderate
    hex: FFC000
  - id: color_poor
    hex: FF7E00
  - id: color_unhealthy
    hex: E72A2A

font:
  - file: gfonts://Montserrat@900
    id: font_value_primary
    size: 80
    bpp: 4
    glyphs: ["0","1","2","3","4","5","6","7","8","9",".","-","n","a"]
  - file: gfonts://Montserrat@800
    id: font_value_secondary
    size: 48
    bpp: 4
    glyphs: ["0","1","2","3","4","5","6","7","8","9",".","-","n","a"]
  - file: gfonts://Montserrat@600
    id: font_label
    size: 20
    bpp: 4
    glyphs: [" ",".","0","1","2","5",A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z]

output:
  - platform: ledc
    id: backlight_pwm
    pin: GPIO15

light:
  - platform: monochromatic
    id: back_light
    output: backlight_pwm
    name: Display
    icon: mdi:cellphone
    restore_mode: ALWAYS_ON
#endregion DISPLAY SETUP

#region DISPLAY
display:
  - platform: mipi_spi
    id: display_main
    model: ILI9341
    cs_pin: GPIO03
    dc_pin: GPIO04
    reset_pin: GPIO06
    dimensions:
      width: 240
      height: 320
    transform:
      mirror_x: false
      mirror_y: true
      swap_xy: false
    color_order: bgr
    invert_colors: false
    pages:
      - id: page_main
        lambda: |-
          auto temperature = id(aht20_temp).state;
          auto co2 = id(co2_scd40).state;
          auto tvoc = id(sgp30_tvoc).state;
          auto pm1 = id(pms_pm1).state;
          auto pm2_5 = id(pms_pm2_5).state;
          auto pm10 = id(pms_pm10).state;

          auto get_color = [](auto value, auto t1, auto t2, auto t3, auto t4) {
            if      (isnan(value)) return id(white);
            else if (value < t1) return id(color_excellent);
            else if (value < t2) return id(color_good);
            else if (value < t3) return id(color_moderate);
            else if (value < t4) return id(color_poor);
            else                 return id(color_unhealthy);
          };

          // Based on https://github.com/KadenThomp36/air-quality-card#health-thresholds
          auto color_co2 = get_color(co2, 600, 800, 1000, 1500);
          auto color_tvoc = get_color(tvoc, 100, 300, 500, 1000);
          auto color_pm10 = get_color(pm10, 15, 45, 75, 150);
          auto color_pm2_5 = get_color(pm2_5, 5, 15, 25, 35);
          auto color_pm1 = get_color(pm1, 5, 15, 25, 35);

          auto w = it.get_width();
          auto h = it.get_height();
          auto offset_y = 5;

          auto draw_divider = [&](int &y) {
            y += offset_y;
            it.line(10, y, w - 10, y, id(dark_gray));
            y += offset_y;
          };

          auto draw_main = [&](int &y) {
            auto col = w / 1;
            auto height_label = id(font_label)->get_height();
            auto height_value = id(font_value_primary)->get_height();

            it.print(0.5 * col, y, id(font_label), id(light_gray), TextAlign::TOP_CENTER, "Temp");
            it.printf(0.5 * col, y + height_label, id(font_value_primary), id(white), TextAlign::TOP_CENTER, "%.1f", temperature);

            y += height_label + height_value;
          };

          auto draw_header = [&](int &y) {
            auto col = w / 2;
            auto height_label = id(font_label)->get_height();
            auto height_value = id(font_value_secondary)->get_height();

            it.print(0.5 * col, y, id(font_label), id(light_gray), TextAlign::TOP_CENTER, "VOC");
            it.printf(0.5 * col, y + height_label, id(font_value_secondary), color_tvoc, TextAlign::TOP_CENTER, "%.0f", tvoc);

            it.print(1.5 * col, y, id(font_label), id(light_gray), TextAlign::TOP_CENTER, "CO2");
            it.printf(1.5 * col, y + height_label, id(font_value_secondary), color_co2, TextAlign::TOP_CENTER, "%.0f", co2);

            y += height_label + height_value;
          };

          auto draw_footer = [&](int &y) {
            auto col = w / 3;
            auto height_label = id(font_label)->get_height();
            auto height_value = id(font_value_secondary)->get_height();

            it.print(0.5 * col, y, id(font_label), id(light_gray), TextAlign::TOP_CENTER, "PM10");
            it.printf(0.5 * col, y + height_label, id(font_value_secondary), color_pm10, TextAlign::TOP_CENTER, "%.0f", pm10);

            it.print(1.5 * col, y, id(font_label), id(light_gray), TextAlign::TOP_CENTER, "PM2.5");
            it.printf(1.5 * col, y + height_label, id(font_value_secondary), color_pm2_5, TextAlign::TOP_CENTER, "%.0f", pm2_5);

            it.print(2.5 * col, y, id(font_label), id(light_gray), TextAlign::TOP_CENTER, "PM1");
            it.printf(2.5 * col, y + height_label, id(font_value_secondary), color_pm1, TextAlign::TOP_CENTER, "%.0f", pm1);

            y += height_label + height_value;
          };

          auto current_y_position = 8;

          draw_header(current_y_position);
          draw_divider(current_y_position);
          draw_main(current_y_position);
          draw_divider(current_y_position);
          draw_footer(current_y_position);
      - id: page_color_test
        lambda: |-
          Color colors[] = {
            id(color_excellent),
            id(color_good),
            id(color_moderate),
            id(color_poor),
            id(color_unhealthy)
          };

          auto w = it.get_width();
          auto h = it.get_height();
          int num_colors = sizeof(colors) / sizeof(colors[0]);
          int bar_height = h / num_colors;

          for (int i = 0; i < num_colors; i++) {
            it.filled_rectangle(0, i * bar_height, w, bar_height, colors[i]);
          }
#endregion DISPLAY
