esphome:
  name: sensorbox
  friendly_name: Sensorbox
  min_version: 2024.6.0
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf
# Enable logging
logger:

# Enable Home Assistant API and failsafe mechanisms
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails, using your wifi's password
  ap:
    ssid: "Sensorbox v2"

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/firmware/esphome-web/esp32s2.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:

debug:
  update_interval: 5s

uart:
  - tx_pin: GPIO10
    rx_pin: GPIO09
    baud_rate: 9600
    id: uart_ze08
    parity: none
    data_bits: 8
    stop_bits: 1
  - tx_pin: GPIO08
    rx_pin: GPIO07
    baud_rate: 9600
    id: uart_pms

spi:
  clk_pin: GPIO01
  mosi_pin: GPIO02
  miso_pin: GPIO16

i2c:
  - sda: GPIO11
    scl: GPIO12
    scan: true
    id: i2c_main

  - sda: GPIO17
    scl: GPIO18
    scan: true
    id: i2c_2

sensor:
  - platform: uptime
    name: "Uptime"
    id: uptime_sensor
    update_interval: 5s
    disabled_by_default: True

  - platform: debug
    free:
      name: "Heap Free"
      id: heap_free
      disabled_by_default: True
    loop_time:
      name: "Loop Time"
      id: loop_time
      disabled_by_default: True

  - platform: aht10
    #address: 0x38
    i2c_id: i2c_main
    variant: AHT20
    temperature:
      name: "Temperature"
      id: temp_aht20
    humidity:
      name: "Humidity"
      id: hum_aht20
    update_interval: 10s

  - platform: bmp280_i2c
    address: 0x77
    i2c_id: i2c_main
    # temperature:
    #   name: "BMP280 Temperature"
    #   id: temp_bmp280
    #   oversampling: 16x
    pressure:
      name: "Pressure"
      id: pres_bmp280
    update_interval: 10s

  - platform: scd4x
    #address: 0x62
    i2c_id: i2c_main
    co2:
      name: "CO2"
      id: co2_scd40
    # temperature:
    #   name: "SCD40 Temperature"
    #   id: temp_scd40
    # humidity:
    #   name: "SCD40 Humidity"
    #   id: hum_scd40
    update_interval: 30s

  - platform: sgp30
    i2c_id: i2c_main
    address: 0x58
    # eco2:
    #   name: "SGP30 eCO2"
    #   id: eco2_sgp30
    #   accuracy_decimals: 0
    #   filters:
    #     - exponential_moving_average:
    #         send_every: 1
    #         alpha: 0.2
    tvoc:
      name: "TVOC"
      id: tvoc_sgp30
      accuracy_decimals: 1
      filters:
        - exponential_moving_average:
            send_every: 1
            alpha: 0.2
    store_baseline: yes
    update_interval: 5s
    compensation:
      humidity_source: hum_aht20
      temperature_source: temp_aht20

  - platform: pmsx003
    type: PMSX003
    update_interval: 120s
    uart_id: uart_pms
    pm_1_0:
      name: "PM1.0"
      id: pm1_pms
    pm_2_5:
      name: "PM2.5"
      id: pm25_pms
    pm_10_0:
      name: "PM10.0"
      id: pm10_pms
