time:
  - platform: homeassistant
    id: time_ha
    timezone: CET-1CEST,M3.5.0,M10.5.0/3

binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected
    entity_category: diagnostic

sensor:
  - platform: uptime
    name: Uptime
    type: timestamp
    time_id: time_ha
    entity_category: diagnostic
  - platform: wifi_signal
    name: RSSI
    update_interval: 60s
    entity_category: diagnostic

button:
  - platform: restart
    icon: mdi:power-cycle
    name: ESP Reboot
    entity_category: diagnostic
  - platform: template
    device_class: identify
    name: Identify
    entity_category: diagnostic
    on_press:
      then:
        - repeat:
            count: 10
            then:
              - output.turn_on: status_led
              - delay: 100ms
              - output.turn_off: status_led
              - delay: 100ms

output:
  - platform: gpio
    pin: GPIO2
    id: status_led

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
